version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/dev/app/Dockerfile
    tty: true
    volumes:
      - ../../:/workspace
    ports:
      - 19000:4000
    env_file:
      - ./.env
