name: Push ieieiei/lpc-api container image to registry

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - release

env:
  IMAGE_NAME: lpc-api

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: extract-metadata
        uses: docker/metadata-action@v4
        with:
          images: ieieiei/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule,prefix=dev-
            type=ref,event=branch,prefix=dev-
            type=ref,event=tag,prefix=dev-
            type=ref,event=pr,prefix=dev-

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./deployments/docker/api.Dockerfile
          push: true
          tags: ${{ steps.extract-metadata.outputs.tags }}
          labels: ${{ steps.extract-metadata.outputs.labels }}
